[Service]
ExecStart=
ExecStart=@JAVA_BIN@ -Xms128m -Xmx768m -Xlog:gc*:file=@PROJECT_ROOT@/logs/backend-gc.log:time,uptime,level,tags:filecount=5,filesize=10M -jar @PROJECT_ROOT@/deploy/backend/@JAR_NAME@ --spring.config.location=file:@PROJECT_ROOT@/config/application-prod.yml
MemoryHigh=900M
MemoryMax=1100M
