[Service]
ExecStart=
ExecStart=@JAVA_BIN@ -Xms128m -Xmx768m -Xlog:gc*:file=@DEPLOY_ROOT@/logs/backend-gc.log:time,uptime,level,tags:filecount=5,filesize=10M -jar @DEPLOY_ROOT@/backend/@JAR_NAME@ --spring.config.location=file:@CONFIG_ROOT@/application-prod.yml
MemoryHigh=900M
MemoryMax=1100M
