#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/frontend/android/app/src/main/AndroidManifest.xml"
CONFIG="$ROOT/frontend/capacitor.config.json"
MONOCHROME_ICON="$ROOT/frontend/android/app/src/main/res/drawable/ic_launcher_monochrome.xml"
CI_WORKFLOW="$ROOT/.github/workflows/ci.yml"
RELEASE_WORKFLOW="$ROOT/.github/workflows/android-release.yml"
RELEASE_CERT="$ROOT/config/android-release-cert.sha256"
RELEASE_VERSION="$ROOT/config/android-release-version.properties"
CAPACITOR_BUILD="$ROOT/frontend/android/app/capacitor.build.gradle"
APP_RELEASE_SOURCE="$ROOT/frontend/src/platform/appRelease.js"

grep -q 'io.github.langxi13.babydiary' "$CONFIG"
grep -q '"androidScheme": "https"' "$CONFIG"
grep -q '"CapacitorCookies"' "$CONFIG"
grep -q "@capacitor/browser" "$ROOT/frontend/package.json"
grep -q "project(':capacitor-browser')" "$CAPACITOR_BUILD"
grep -q 'Browser.open' "$APP_RELEASE_SOURCE"
grep -q 'android:allowBackup="false"' "$MANIFEST"
grep -q 'android:fillType="evenOdd"' "$MONOCHROME_ICON"
grep -q '<monochrome android:drawable="@drawable/ic_launcher_monochrome"' "$ROOT/frontend/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml"
grep -q '<monochrome android:drawable="@drawable/ic_launcher_monochrome"' "$ROOT/frontend/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml"
grep -q '^google-services\.json$' "$ROOT/frontend/android/.gitignore"
! grep -q 'android.intent.action.SEND' "$MANIFEST"
! test -e "$ROOT/frontend/android/app/src/main/java/io/github/langxi13/babydiary/NativeShareReceiverPlugin.java"
! test -e "$ROOT/frontend/src/platform/nativeShareInbox.js"
! grep -q '<external-path' "$ROOT/frontend/android/app/src/main/res/xml/file_paths.xml"
grep -q 'Java 21' "$ROOT/scripts/build-android.sh"
grep -q -- '--no-daemon --max-workers' "$ROOT/scripts/build-android.sh"
grep -q 'cmdline-tools/latest/bin/sdkmanager' "$CI_WORKFLOW"
grep -q 'cmdline-tools/latest/bin/sdkmanager' "$RELEASE_WORKFLOW"
! grep -Eq 'run: sdkmanager ' "$CI_WORKFLOW" "$RELEASE_WORKFLOW"
grep -Eq '^[0-9a-f]{64}$' "$RELEASE_CERT"
grep -Eq '^VERSION_CODE=[1-9][0-9]*$' "$RELEASE_VERSION"
grep -Eq '^VERSION_NAME=[0-9]+(\.[0-9]+){1,3}([.-][A-Za-z0-9]+)*$' "$RELEASE_VERSION"
grep -q 'android-release-cert.sha256' "$RELEASE_WORKFLOW"
grep -q 'android-release-version.properties' "$RELEASE_WORKFLOW"
grep -q 'steps.release_version.outputs.version_code' "$RELEASE_WORKFLOW"
grep -q 'Android signing certificate does not match the pinned release certificate' "$RELEASE_WORKFLOW"
grep -q 'contents: write' "$RELEASE_WORKFLOW"
grep -q 'gh release create' "$RELEASE_WORKFLOW"
grep -q 'Android release tag already exists and will not be overwritten' "$RELEASE_WORKFLOW"
test -x "$ROOT/scripts/ensure-android-signing.sh"
test -x "$ROOT/scripts/sync-android-signing-secrets.sh"
test -x "$ROOT/scripts/build-android-release.sh"
test -x "$ROOT/scripts/verify-android-artifact.sh"
test -x "$ROOT/scripts/publish-android-update.sh"
grep -q -- '--no-daemon --max-workers' "$ROOT/scripts/build-android-release.sh"
grep -q 'lintRelease testDebugUnitTest assembleRelease bundleRelease' "$ROOT/scripts/build-android-release.sh"
grep -q 'verify-android-artifact.sh' "$ROOT/scripts/build-android-release.sh"
grep -q 'verify-android-artifact.sh' "$RELEASE_WORKFLOW"
grep -q 'APK certificate does not match the pinned Android release certificate' "$ROOT/scripts/verify-android-artifact.sh"
grep -q 'AAB certificate does not match the pinned Android release certificate' "$ROOT/scripts/verify-android-artifact.sh"
grep -q 'android:usesCleartextTraffic.*0x0' "$ROOT/scripts/verify-android-artifact.sh"

echo "native Android shell, secure session, gallery, and camera actions are tracked"
